pub const ENV_HL_HOME: &str = "HL_HOME";

pub const ENV_HYPERLIQUID_PRIVATE_KEY: &str = "HYPERLIQUID_PRIVATE_KEY";
pub const ENV_HYPERLIQUID_KEYSTORE: &str = "HYPERLIQUID_KEYSTORE";
pub const ENV_HYPERLIQUID_KEYSTORE_PASSWORD: &str = "HYPERLIQUID_KEYSTORE_PASSWORD";
